const actionTypes = {
  SET_PERIOD: 'SET_PERIOD',
  SET_GROSS_SALARY: 'SET_GROSS_SALARY',
  SET_BENEFIT: 'SET_BENEFIT',
  SET_GROSS_INCOME: 'SET_GROSS_INCOME',
  SET_EXPENSE: 'SET_EXPENSE',
  SET_FLAT_EXPENSE_RATE: 'SET_FLAT_EXPENSE_RATE',
  SET_SICKNESS_INSURANCE_ENABLED: 'SET_SICKNESS_INSURANCE_ENABLED',
  SET_UNPAID_DAYS: 'SET_UNPAID_DAYS',
};

export default actionTypes;
