const actionTypes = {
  SET_TAX_PAYER_TYPE: 'SET_TAX_PAYER_TYPE',
  SET_PERIOD: 'SET_PERIOD',
  SET_INCOME: 'SET_INCOME',
  SET_BENEFIT: 'SET_BENEFIT',
  SET_EXPENSE: 'SET_EXPENSE',
  SET_FLAT_EXPENSE_RATE: 'SET_FLAT_EXPENSE_RATE',
  SET_SICKNESS_INSURANCE: 'SET_SICKNESS_INSURANCE',
};

export default actionTypes;
