const actionTypes = {
  SET_TAX_PAYER_TYPE: 'SET_TAX_PAYER_TYPE',
  SET_INCOME: 'SET_INCOME',
  SET_EXPENSE: 'SET_EXPENSE',
  SET_FLAT_EXPENSE_RATE: 'SET_FLAT_EXPENSE_RATE',
};

export default actionTypes;
